version: "3.7"

services:
  app-server:
    container_name: JavaBackend
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lagaltdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - backend
      - frontend

  app-client:
    container_name: ReactFront
    build:
      context: client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api/v1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
      - ./nginx/var/www/html:/var/www/html
      - ./logs/nginx/:/var/log/nginx:rw
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      #     - Certbot-conf:/etc/letsencrypt
      #     - Certbot-www:/var/www/certbot
    hostname: www.Lag-alt.no
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  db:
    container_name: postgresDB
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lagaltdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:
  Certbot-conf:
  Certbot-www:

networks:
  backend:
  frontend:
    driver: “bridge”
